### ISSUE TITLE
What's difference between it and percollate?

### ISSUE THREAD

**Issue by emersonlaurentino** [vladocar/PDFSave#2]
https://github.com/danburzo/percollate

**Comment by vladocar** [comment]
PDFSave is text only and it generates "light" PDF documents. Also they use different node modules for parsing and generating the PDF file.

Here is percollate works: https://github.com/danburzo/percollate#how-it-works

PDFSave uses: node-readability for clearing and parsing. Pdfkit is used for PDF generation.
